version: "3.8"

services:
  go:
    container_name: gateway
    working_dir: /app
    tty: true
    build:
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - 8080:8080
    command: sh -c 'go mod tidy && air'
